spring:
  application:
    name: toon-world
  datasource:
    url: jdbc:mariadb://${DATABASE_HOST}/${DATABASE_SCHEMA}?serverTimezone=UTC
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC
          batch_size: 50
        order_inserts: true
    show-sql: false

logging:
  level:
    de.hydrum: TRACE

app:
  sync:
    player:
      delay-in-seconds: 21600 # 6 * 60 * 60 # 6 hours
      error-delay-in-seconds: 300 # 5 * 60 # 5 min
    guild:
      delay-in-seconds: 21600 # 6 * 60 * 60 # 6 hours
      error-delay-in-seconds: 300 # 5 * 60 # 5 min
    unit:
      fixed-delay-in-milliseconds: 86400000 # 24 * 60 * 60 * 1000 # 24 hours
      initial-delay-in-milliseconds: 0
  api:
    swgohgg:
      base-url: "https://swgoh.gg/api"
    comlink:
      base-url: "http://comlink:3000"
  discord:
    bot-token: ${DISCORD_TOKEN}
    super-admin:
      guild: "1230541668680339597"
      test-channel: "1230542316242993224"
      error-channel: "1230542316242993224"
    officer-roles:
      - "1341800031870779392" # OWNER in superadmin
      - "799758807139876914" # Officer in Snackbar Elite
  cache:
    expire-after-write-in-minutes: 1440
  data:
    mod-file: game-data-mods_20250110.json
    journey-guide-file: journey-guide.json

commands:
  player-progress:
    default-from: 7
    default-to: